Yd 19
YetiForceCompany/YetiForceDoc pull request #149
Opened 2024-06-17 14:47 UTC by RubenLech

2024-06-19 13:13 UTC, mariuszkrzaczkowski commented on i18n/pl/docusaurus-plugin-content-docs/current/3-administrator-guides/04-marketplace/02-addons/01-branding/README.md
> +Umożliwia dodanie istotnych informacji do generowanych dokumentów, wstawienie danych swojej firmy do stopki lub ustawienie własnych linków do profili w mediach społecznościowych.
Umożliwia dodanie istotnych informacji do generowanych dokumentów

2024-06-19 13:17 UTC, mariuszkrzaczkowski commented on i18n/pl/docusaurus-plugin-content-docs/current/3-administrator-guides/04-marketplace/02-addons/01-branding/README.md
> +### Funkcje
dodainfo o ukryci danych

2024-06-25 13:41 UTC, rskrzypczak commented on docs/3-administrator-guides/04-marketplace/02-addons/01-branding/README.md
> +Ikony mediów społecznościowych nie pokażą się w stopce jeśli pole na link do danego profilu nie zostanie wypełnione.
```suggestion
Ikony mediów społecznościowych nie pokażą się w stopce, jeśli odnośniki nie zostały uzupełnione w konfiguracji.
```

2024-06-25 13:44 UTC, rskrzypczak commented on i18n/pl/docusaurus-plugin-content-docs/current/3-administrator-guides/04-marketplace/02-addons/01-branding/branding-3.jpg
uzupełnij jakieś dane w zakładce brandingu, np. `Twoja Nazwa Firmy` itp. aby pokazać, ze możesz manipulować treścią w stopce.

2024-06-25 13:48 UTC, rskrzypczak commented on i18n/pl/docusaurus-plugin-content-docs/current/3-administrator-guides/04-marketplace/02-addons/01-branding/README.md
> +### Czy usługa Disable Branding pozwala zmienić logo w systemie?
Zamienić na FQA - Często zadawane pytania
coś jat tutaj: https://yetiforce.com/pl/polskie-rejestry.html#:~:text=WSZYSTKO%20CO%20MUSISZ%20WIEDZIE%C4%86%C2%A0O

2024-06-26 07:39 UTC, mariuszkrzaczkowski requested changes

2024-06-26 07:39 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/04-marketplace/02-addons/01-branding/README.md
> +### Funkcje
zawsze przed/pod nagłówkami musi być pusty wiersz

2024-06-26 07:39 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/04-marketplace/02-addons/01-branding/README.md
> +### Personalizacja informacji widocznych w stopce strony
zawsze przed/pod nagłówkami musi być pusty wiersz

2024-06-26 07:39 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/04-marketplace/02-addons/01-branding/README.md
> +### Czy usługa Disable Branding pozwala zmienić logo w systemie?
zawsze przed/pod nagłówkami musi być pusty wiersz

2024-06-26 07:39 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/04-marketplace/02-addons/01-branding/README.md
> +![branding-2](branding-2.jpg)
błąd składniowy  Markdown,  albo nowy wiersz albo zdjęcie na końcu zdania

2024-06-26 07:39 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/04-marketplace/02-addons/01-branding/README.md
> +![branding-3](branding-3.jpg)
błąd składniowy  Markdown,  albo nowy wiersz albo zdjęcie na końcu zdania

2024-06-26 07:43 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/04-marketplace/02-addons/01-branding/README.md
> +
brak keywords oraz tags, super jak by dało radę dodać zdjęcie w preview

2024-07-04 13:54 UTC, closed without merging