YD-23 standard widgets
YetiForceCompany/YetiForceDoc pull request #150
Opened 2024-06-19 06:39 UTC by RubenLech

2024-06-21 06:15 UTC, rskrzypczak requested changes

2024-06-21 06:15 UTC, rskrzypczak commented on docs/3-administrator-guides/06-standard-modules/03-standard-widgets/02-widgets-from-filters.md
> +W oknie modalnym, które się pojawi wybierz moduł zgodny z modułem, w którym został utworzony filtr i uzupełnij pozostałem informacje niezbędne do działania widgetu.
```suggestion
W oknie modalnym, które się pojawi wybierz moduł zgodny z modułem, w którym został utworzony filtr i uzupełnij pozostałe informacje niezbędne do działania widgetu.
```

2024-06-21 06:15 UTC, rskrzypczak commented on docs/3-administrator-guides/06-standard-modules/03-standard-widgets/README.md
> +Widgety oparte o filtry stworzone na listach pozwalają na prezentację danych zgodnie z indywidualnie przyjętymi założeniami i ograniczeniami.
```suggestion
Widgety oparte o filtry pozwalają na prezentację danych zgodnie z indywidualnie przyjętymi założeniami i ograniczeniami. 
```

2024-06-26 08:09 UTC, mariuszkrzaczkowski requested changes

2024-06-26 08:09 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/06-standard-modules/03-standard-widgets/02-widgets-from-filters.md
> +Po kliknięciu przycisku "Stwórz nowy filtr" w widoku listy, pojawia się okno modalne, które oferuje szeroki wachlarz opcji dostosowywania i filtrowania danych.
każdy tekst/ikona przycisku umieść w kbd

2024-06-26 08:09 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/06-standard-modules/03-standard-widgets/02-widgets-from-filters.md
> +Widget z filtru można utworzyć w systemie YetiForce CRM na dwa sposoby.
jeśli dobrze pamiętam to nie piszemy CRM  @rskrzypczak ? tylko samo YetiForce

2024-06-26 08:09 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/06-standard-modules/03-standard-widgets/02-widgets-from-filters.md
> +### Tworzenie widgetu przez panel administracyjny
zawsze przed/pod nagłówkami musi być pusty wiersz

2024-06-26 08:09 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/06-standard-modules/03-standard-widgets/02-widgets-from-filters.md
> +Następnie dla odpowiedniego pulpitu i roli wybierz przycisk **Widget z filtrem**
każdy tekst/ikona przycisku umieść w kbd

2024-06-26 08:09 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/06-standard-modules/03-standard-widgets/02-widgets-from-filters.md
> +Następnie należy przejść w Panelu użytkownika do zakładki Pulpit i dodać widget wybierając go z listy, która się pojawi po naciśnięciu przycisku **Predefiniowane widgety**
każdy tekst/ikona przycisku umieść w kbd

2024-06-26 08:09 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/06-standard-modules/03-standard-widgets/02-widgets-from-filters.md
> +W tym celu przejdź do zakładki **Pulpit** a następnie wybierz przycisk **Dodaj widget z filtru**.
każdy tekst/ikona przycisku umieść w kbd

2024-06-26 08:09 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/06-standard-modules/03-standard-widgets/02-widgets-from-filters.md
> +Podobnie jak to miało miejsce w podczas tworzenia widgetu przez Panel administracyjny, pojawi nam się okno modalne, w którym możemy ustalić szczegóły tworzonego widgetu.
Panel administracyjny jako link do części admina

2024-06-26 08:09 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/06-standard-modules/03-standard-widgets/03-chars.md
> +title: Wykresy z filtrów
brak description, keywords oraz tags, super jak by dało radę dodać zdjęcie w preview

2024-06-26 08:09 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/06-standard-modules/03-standard-widgets/04-widgets-on-record.md
> +title: Widgety na rekordzie
brak description, keywords oraz tags, super jak by dało radę dodać zdjęcie w preview

2024-06-26 08:09 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/06-standard-modules/03-standard-widgets/03-chars.md
> +W celu utworzenia wykresu z filtru przejdź do zakładki **Pulpit** a następnie wybierz przycisk **Dodaj wykres z filtru**.
błąd składniowy Markdown, nowy wiersz albo tekst na końcu zdania

2024-06-26 08:09 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/06-standard-modules/03-standard-widgets/03-chars.md
> +Pojawi nam się wówczas okno modalne, w którym możemy ustalić szczegóły tworzonego wykresu.
błąd składniowy Markdown, nowy wiersz albo tekst na końcu zdania

2024-06-26 08:09 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/06-standard-modules/03-standard-widgets/04-widgets-on-record.md
> +* Następnie kliknij **Moduły - Widżety**
każdy tekst/ikona przycisku umieść w kbd

2024-06-26 08:09 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/06-standard-modules/03-standard-widgets/04-widgets-on-record.md
> +* Kliknij przycisk **Dodaj Widget**.
każdy tekst/ikona przycisku umieść w kbd

2024-06-26 08:09 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/06-standard-modules/03-standard-widgets/README.md
> +title: Widgety Standardowe
brak description, keywords oraz tags, super jak by dało radę dodać zdjęcie w preview

2024-06-26 08:15 UTC, mariuszkrzaczkowski requested changes

2024-06-26 08:15 UTC, mariuszkrzaczkowski commented on docs/3-administrator-guides/06-standard-modules/03-standard-widgets/README.md
> +## [Widgety z filtrem](/administrator-guides/standard-modules/standard-widgets/widgets-from-filters)
To można zamienić na
 ```
import DocCardList from '@theme/DocCardList';
```
Wtedy automatycznie wygeneruje listę z opisem  z pozostałych plików md

2024-06-27 13:12 UTC, rskrzypczak commented on docs/3-administrator-guides/06-standard-modules/03-standard-widgets/04-widgets-on-record.md
> +Oprócz widgetów umieszczanych na pulpicie nawigacyjnym, YetiForce oferuje również możliwość dodawania widgetów w szczegółach poszczególnych rekordów z listy. Funkcja ta pozwala na spersonalizowanie w
```suggestion
Oprócz widgetów umieszczanych na pulpicie nawigacyjnym, YetiForce oferuje również możliwość dodawania widgetów w szczegółach poszczególnych rekordów. Funkcja ta pozwala na spersonalizowanie widoku i szybki dostęp do najważniejszych informacji dotyczących danego elementu, bez konieczności przechodzenia do innych modułów.
```

2024-07-04 07:39 UTC, merged