YD-15 API
YetiForceCompany/YetiForceDoc pull request #176
Opened 2024-07-11 09:45 UTC by RubenLech

2024-08-29 09:12 UTC, rskrzypczak requested changes
Prośba o weryfikację plików w katalogu EN, aby treści były w EN

2024-08-29 09:12 UTC, rskrzypczak commented on i18n/en/docusaurus-plugin-content-docs/current/4-developer-guides/2-api/0-config.md
doc w wersji PL, a powinien być w EN

2024-08-29 09:12 UTC, rskrzypczak commented on i18n/en/docusaurus-plugin-content-docs/current/4-developer-guides/2-api/1-first-connect.mdx
doc w katalogu EN, a jest napisany w PL

2024-09-02 05:53 UTC, mariuszkrzaczkowski commented on docs/4-developer-guides/2-api/0-config.md
> -## Konfiguracja żywotność sesji
czemu to usunięto ?

2024-09-02 05:53 UTC, mariuszkrzaczkowski commented on docs/4-developer-guides/2-api/0-config.md
> -## Aktywacja
czemu to usunięto ?

2024-09-02 05:53 UTC, mariuszkrzaczkowski commented on docs/4-developer-guides/2-api/1-first-connect.mdx
> +* [Webservice Standard](/developer-guides/api/WebserviceStandard)
to bym wygenerował z automatu za pomocą openapi

2024-09-02 05:54 UTC, mariuszkrzaczkowski commented on docs/4-developer-guides/2-api/2-how-to-add-graphic-file.md
> ----
czemu usuwany jest plik PL iw to miejsce dawany EN ?

2024-09-16 09:07 UTC, merged